name: staging

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup build
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build and deploy Worker
        uses: cloudflare/wrangler-action@v4
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            API_TOKEN
          environment: staging

      - name: Run database migrations
        uses: cloudflare/wrangler-action@v4
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: staging
          command: d1 migrations apply weather_staging --remote
